Improve the box styles according to the specs
wmde/query-builder pull request #143
Opened 2021-01-08 20:57 UTC by Ladsgroup

- Improve responsiveness by removing the extra padding when the boxes
   are stacking on top of each other.
 - Add border based on the specs

2021-01-11 09:17 UTC, guergana commented
Hi, Amir, where are the specs? I don't see the gray border in figma.

2021-01-11 09:39 UTC, micgro42 requested changes
Thanks for those adjustments! Just the border radius is missing, I think :)

The specs have been added to here https://www.figma.com/file/hZpaYX0xNNhK0L7kBvN6WK/Query-Builder?node-id=2604%3A29420

2021-01-11 09:39 UTC, micgro42 commented on src/components/QueryBuilder.vue
> +	border: $border-width-thin $border-style-base $border-color-base-default;
I think they still need the `$border-radius-base`

2021-01-11 13:56 UTC, Ladsgroup commented
> Thanks for those adjustments! Just the border radius is missing, I think :)
> 
> The specs have been added to here https://www.figma.com/file/hZpaYX0xNNhK0L7kBvN6WK/Query-Builder?node-id=2604%3A29420

Oh thanks. They didn't exist in the CSS but they are added as a note (that's why I missed that)
![image](https://user-images.githubusercontent.com/5351225/104190992-34b51700-541d-11eb-8353-f14fe75a2369.png)

2021-01-12 09:19 UTC, micgro42 approved these changes
Ready to go :)

2021-01-12 09:19 UTC, merged