Layout adjustments for the tiniest viewport
wmde/query-builder pull request #144
Opened 2021-01-11 10:24 UTC by micgro42

This should be merged after #143 

Inspired by the styles in https://www.figma.com/file/hZpaYX0xNNhK0L7kBvN6WK/Query-Builder?node-id=2604%3A29422

The viewport breakpoint has been chosen so that the inputs don't align as next to each other again in the smallest layout.

Also, the outer padding was too large still even for larger viewports. It should be `-small`, not `-xlarge`.

Bug: [T269470](https://phabricator.wikimedia.org/T269470)

2021-01-11 15:27 UTC, guergana requested changes, later dismissed
The outer spacing of the component in desktop are now gone.

2021-01-12 09:58 UTC, micgro42 commented
> The outer spacing of the component in desktop are now gone.

Fixed now, I used a spacing token instead of a layout token.

2021-01-12 17:48 UTC, Ladsgroup commented
I might be doing it wrong but when I pulled the branch and ran it, it still got the error in 290px:
![image](https://user-images.githubusercontent.com/5351225/104352207-ac12a580-5506-11eb-885d-b0a2abebda9a.png)

2021-01-13 09:10 UTC, micgro42 commented
> I might be doing it wrong but when I pulled the branch and ran it, it still got the error in 290px:
> ![image](https://user-images.githubusercontent.com/5351225/104352207-ac12a580-5506-11eb-885d-b0a2abebda9a.png)

Yeah. that's ok. We don't support screens below 320px. We have to stop somewhere.

2021-01-13 13:54 UTC, Ladsgroup commented
Aha, I had the issue with 370px before and I thought it's the same. Missed the 100px difference.

2021-01-13 13:54 UTC, Ladsgroup approved these changes

2021-01-13 14:23 UTC, merged