Fix for dropdown always changing to matching on validation
wmde/query-builder pull request #87
Opened 2020-11-30 12:19 UTC by guergana

2020-11-30 13:11 UTC, Ladsgroup requested changes
I added that line for another edge case, it's when you use a property with limited support but then change it to another property with full support, without this line, the fields stay disabled. This should fix it in another way.

2020-11-30 14:01 UTC, guergana commented
> I added that line for another edge case, it's when you use a property with limited support but then change it to another property with full support, without this line, the fields stay disabled. This should fix it in another way.

I think the logic of this function needs to be re-thought because right now it's asking to change to matching whenever the property value has a value, which is not correct.

2020-12-01 10:49 UTC, guergana reviewed
Looks good.

2020-12-01 10:51 UTC, Ladsgroup approved these changes

2020-12-01 10:51 UTC, merged